export const CONNECTION_SUCCESS = 'CONNECTION_SUCCESS';
export const CONNECTION_FAILED = 'CONNECTION_FAILED';
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED';
export const CONNECTION_RESET = 'CONNECTION_RESET';

export const JOIN_SESSION_BEGIN = 'JOIN_SESSION_BEGIN';
export const JOIN_SESSION_SUCCESS = 'JOIN_SESSION_SUCCESS';
export const JOIN_SESSION_FAILED = 'JOIN_SESSION_FAILED';

export const RECEIVED_SCREENSHOT = 'RECEIVED_SCREENSHOT';

export const RESET_JOIN_ERROR = 'RESET_JOIN_ERROR';

export const FILE_RECEIVED = 'FILE_RECEIVED';
export const DELETE_FILES = 'DELETE_FILES';